  steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/searce-01/helloworld', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/searce-01/helloworld']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run', '--image', 'gcr.io/searce-01/helloworld', '--europe-west1', '']
images:
- gcr.io/searce-01/helloworld
